apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.11.0
      sourceRef:
        name: hashicorp-helm
        kind: HelmRepository
      interval: 1m
  values:
    server:
      dev:
        enabled: true
